services:
  - type: web
    name: sayabur-laravel
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildFilter:
      paths: ["Dockerfile"]
    autoDeploy: true
    healthCheckPath: /
