services:
  - type: web
    name: Sayaburguer-3
    buildCommand: |
      composer install --no-dev --optimize-autoloader
    startCommand: |
      php artisan migrate --force && php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_NAME
        value: Laravel
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:+jQOn8teLJjfICfrtmDCT6AMAtRvc4Qdz2CZjDL/36Y=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://sayaburguer-3.onrender.com

      - key: APP_LOCALE
        value: es
      - key: APP_FALLBACK_LOCALE
        value: en
      - key: APP_FAKER_LOCALE
        value: en_US

      - key: PHP_CLI_SERVER_WORKERS
        value: 4
      - key: BCRYPT_ROUNDS
        value: 12
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_STACK
        value: single
      - key: LOG_DEPRECATIONS_CHANNEL
        value: null
      - key: LOG_LEVEL
        value: debug

      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: sayaburguer-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: sayaburguer-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: sayaburguer-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: sayaburguer-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: sayaburguer-db
          property: password

      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120
      - key: SESSION_ENCRYPT
        value: false
      - key: SESSION_PATH
        value: /
      - key: SESSION_DOMAIN
        value: null

      - key: BROADCAST_CONNECTION
        value: log
      - key: FILESYSTEM_DISK
        value: local
      - key: QUEUE_CONNECTION
        value: database

      - key: CACHE_STORE
        value: database

      - key: MEMCACHED_HOST
        value: 127.0.0.1

      - key: REDIS_CLIENT
        value: phpredis
      - key: REDIS_HOST
        value: 127.0.0.1
      - key: REDIS_PASSWORD
        value: null
      - key: REDIS_PORT
        value: 6379

      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: cristhian.silva@tecsup.edu.pe
      - key: MAIL_PASSWORD
        value: jhvdfnsjoovlfydo
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: cristhian.silva@tecsup.edu.pe
      - key: MAIL_FROM_NAME
        value: "Saya Burguer"

      - key: AWS_ACCESS_KEY_ID
        value: ""
      - key: AWS_SECRET_ACCESS_KEY
        value: ""
      - key: AWS_DEFAULT_REGION
        value: us-east-1
      - key: AWS_BUCKET
        value: ""
      - key: AWS_USE_PATH_STYLE_ENDPOINT
        value: false

      - key: VITE_APP_NAME
        value: Laravel

      - key: PAYPAL_CLIENT_ID
        value: AVuKm9qi6S9JfyqmNZ4xmOdJ6m8SHMKPA-e03btcWPZmq8Z44G2FETkWwbnYIYXE9HQwazDqCHJiudtt
      - key: PAYPAL_CLIENT_SECRET
        value: EGKvVfqevwf3h95pM3A_1Zu4M4VQLge__NEbg6kqGIBh-0_GD6OaOALkGIvWaJ93jno2z1iyYWtOEo5Z
      - key: PAYPAL_MODE
        value: sandbox

databases:
  - name: sayaburguer-db
    plan: free
