services:
  - type: web
    name: sayaburguer-4
    plan: free
    env: docker
    envVars:
      - key: APP_NAME
        value: SayaBurger
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://sayaburguer-4.onrender.com
      - key: APP_KEY
        value: base64:+jQOn8teLJjfICfrtmDCT6AMAtRvc4Qdz2CZjDL/36Y=
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: containers-us-west-111.railway.app
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: lfQsgmlmMZhKTXxwLUrmXQtzyyzvuMUS
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: cristhian.silva@tecsup.edu.pe
      - key: MAIL_PASSWORD
        value: jhvdfnsjoovlfydo
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: cristhian.silva@tecsup.edu.pe
      - key: MAIL_FROM_NAME
        value: Saya Burguer
      - key: PAYPAL_CLIENT_ID
        value: AVuKm9qi6S9JfyqmNZ4xmOdJ6m8SHMKPA-e03btcWPZmq8Z44G2FETkWwbnYIYXE9HQwazDqCHJiudtt
      - key: PAYPAL_CLIENT_SECRET
        value: EGKvVfqevwf3h95pM3A_1Zu4M4VQLge__NEbg6kqGIBh-0_GD6OaOALkGIvWaJ93jno2z1iyYWtOEo5Z
      - key: PAYPAL_MODE
        value: sandbox
